spring.datasource.url=jdbc:mariadb://np.imchobo.com:3306/rental
spring.datasource.username=rental
spring.datasource.password=user123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
